### ISSUE TITLE
Add my Lady Dog

### ISSUE THREAD

**Issue by analistasp** [jigsawpieces/dog-api-images#139]
Her is a Coated Retriever 
![Preta](https://user-images.githubusercontent.com/66397682/99684974-d5600980-2a60-11eb-84c4-0bbb27a462b3.JPG)

**Comment by jigsawpieces** [comment]
Wow she looks like a great dog! However we do not accept submissions in this format - please can you make a PR and add her to the appropriate folder please? Thanks!
