### ISSUE TITLE
links

### ISSUE THREAD

**Issue by Scroll-down** [jigsawpieces/dog-api-images#145]
hey can you make a folder that just has the jpeg links

**Comment by monsieurbaguette** [comment]
Why would you need this put in the repository? If you just need a list of JPEG links, you can write a program that outputs the links to each image in the API (as far as I know you can only list the image links of individual breeds through the API, so you would need to write a program that retrieves that list for each breed). Lists of image links (in JSON format) for specific breeds can be obtained by visiting or making an HTTP request to https://dog.ceo/api/breed/{breed/sub-breed}/images for each breed.
