### ISSUE TITLE
Add more pug pics

### ISSUE THREAD

**Issue by MistyCanCode** [jigsawpieces/dog-api-images#214]
![bobmarley](https://user-images.githubusercontent.com/46390494/171262302-6b308735-9cae-4054-a07e-02a7c0504e3d.jpg)
![willienelson](https://user-images.githubusercontent.com/46390494/171262325-7a38c2f3-a079-4d7d-ba48-e0b962dda0c9.jpg)

Two pictures for the pug category, Bob Marley, age 7, and Willie Nelson, age 8.

Please and thank you!

**Comment by jigsawpieces** [comment]
Hi! Please submit images of dogs as a PR rather than an issue, thanks!
