### ISSUE TITLE
No file size guidelines about contributing photos

### ISSUE THREAD

**Issue by Kernix13** [jigsawpieces/dog-api-images#244]
What are the recommended sizes you want for photos? I have pictures of my dog, an American Staffordshire (Pitbull) as 600px x 400px but I also have huge versions of those images. I would think smaller is better. Do you have a preference?

**Comment by jigsawpieces** [comment]
> What are the recommended sizes you want for photos? I have pictures of my dog, an American Staffordshire (Pitbull) as 600px x 400px but I also have huge versions of those images. I would think smaller is better. Do you have a preference?

Hi @Kernix13, the only suggestion we have around image size is that it's should be under 300kb, see: https://github.com/jigsawpieces/dog-api-images#submission-guide

**Comment by Kernix13** [comment]
Got it, thanks!
