### ISSUE TITLE
dog-api-images to host pictures only containing dogs

### ISSUE THREAD

**Issue by edegaudenzi** [jigsawpieces/dog-api-images#254]
Hi everyone, 

I landed on this wonderful idea/project because I needed to see random pictures of dogs on demand; I even submitted couple of pictures myself to contribute to the gallery.

**Problem**
I can define myself as an average user and I can't tell the surprise when I saw people and even children, in the random pictures. Useless to say that I don't think this is the correct place to host pictures of humans, even if in company of their 4pawed treasures. What do you think about this guys?
Also, it can (will?) become a legal issue: hosting non-explicitly-authorised pictures of kids can be legally persecuted; this also applies to adults.

**Solution**
- In the README.md file - **Submission guide** section - Add in an additional line mentioning that pictures only containing dogs will be accepted.
- Remove all of the existing pictures that include partial or total human figures, even if the human is not recognisable. This would give a first _dog-only orientation_ to the dog-api-images project.
- When accepting a pull request in future, enforce this clause, asking the contributor to remove possible human-including pictures added by mistake.

**Comment by jigsawpieces** [comment]
@edegaudenzi I think that is a great idea! Feel free to open a PR with suggested updates to the README.md file and we can continue from there.

**Comment by edegaudenzi** [comment]
@jigsawpieces a couple of weeks ago I've created a pull request to solve this issue, also listing all of the existing pictures containing human in a comment; as you can imagine this took a while to complete across 20000 images!
Today @ElliottLandsborough tossed it away without a comment. Is there any explanation?

**Comment by jigsawpieces** [comment]
Hi @edegaudenzi - I'm not sure why your original PR was closed - must've been by accident. I'm reviewing it now and will create a new PR to remove the blacklisted images. Thank you so much for your (and your wife!) help in scanning the whole image set 🙂

**Comment by jigsawpieces** [comment]
Hi @edegaudenzi have removed images you identified in https://github.com/jigsawpieces/dog-api-images/pull/274 and also updated README in https://github.com/jigsawpieces/dog-api-images/pull/275 - I think the original PR was closed due to a git history clashes as default branch was changed from `master` to `main` during the two weeks it had been open for. Thanks for your contributions to making this repository a better and more GDPR compliant for all users 🙂

**Comment by jigsawpieces** [comment]
Closing this issue now as feels like it has been resolved - feel free to re-open or create a new issue if more discussion is needed.

**Comment by edegaudenzi** [comment]
@jigsawpieces, I'm glad to have been useful and thank for investigating and sorting out the issue with the merges.
