### ISSUE TITLE
403 error when attempting to create pr to add doggo pics

### ISSUE THREAD

**Issue by hboyle2** [jigsawpieces/dog-api-images#262]
Perhaps its user error?  Not sure but I'm getting: _unable to access 'https://github.com/jigsawpieces/dog-api-images.git/': The requested URL returned error: 403_ when trying to push up a pr

**Comment by ElliottLandsborough** [comment]
You will need to fork the repository to make a pull request.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
