### ISSUE TITLE
New dog images added a few days ago are not showing up in API requests 

### ISSUE THREAD

**Issue by emadel1990** [jigsawpieces/dog-api-images#266]
Hi! I added a few images from my dog Sasha a few days ago. The PR was approved and succesfully merged, but when i try to fetch the data from the API, the images doesn't show up. Is there some CI/CD to run or what is happening?

**Comment by ElliottLandsborough** [comment]
The directory layout was a bit confusing as I had left a file in a folder called 'golden' which was only meant for testing.

I have moved your images to the correct folder so they should start appearing under the golden retriever section in a few hours.

https://github.com/jigsawpieces/dog-api-images/commit/763cebb0491b81fe3db8ed3434bcf630992f26ad
