### ISSUE TITLE
Category/Breed-List.

### ISSUE THREAD

**Issue by Yasir-Khan22** [jigsawpieces/dog-api-images#282]
Consider adding Bully kutta's category/breed list. Bully Kutta, also known as Pakistani Mastiff.

**Comment by jigsawpieces** [comment]
Hey @Yasir-Khan22 , go for it! If you have a picture of a Pakistani Mastiff, feel free to raise a PR and add the folder yourself 🐶 😄

**Comment by jigsawpieces** [comment]
Closing as issue can be resolved by opener by opening a PR containing a image of the new breed in question.
