### ISSUE TITLE
 invalid path error when trying to clone repo ( error: invalid path 'dachshund/gofetchbot_Jubi_2023-03-06T01:55:58Z.jpg')

### ISSUE THREAD

**Issue by ad3rinto** [jigsawpieces/dog-api-images#297]
When trying to clone a repo to local environment the following error is produced.

> error: invalid path 'dachshund/gofetchbot_Jubi_2023-03-06T01:55:58Z.jpg'
> fatal: unable to checkout working tree
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry with 'git restore --source=HEAD :/'

This prevents the files from downloading to local repository.
A workaround is to delete the file  'dachshund/gofetchbot_Jubi_2023-03-06T01:55:58Z.jpg'  and the "pull.

**Comment by ElliottLandsborough** [comment]
File has been renamed. If you pull the latest commit it will be fixed.

**Comment by ad3rinto** [comment]
Thanks. .
Now fixed.
