### ISSUE TITLE
missing image

### ISSUE THREAD

**Issue by donavon** [jigsawpieces/dog-api-images#52]
When hitting this api https://dog.ceo/api/breeds/image/random/alt I received `url` that returned a 404. The `url` was https://images.dog.ceo/breeds/mix/Houdini-border-collie-mix

**Comment by ElliottLandsborough** [comment]
Hi @donavon - this has been fixed.

Looks like we have a caching issue which I am looking into as a result of your ticket.

Thanks for contributing!

Note to self: Write some tests to make sure the github repo has been correctly mirrored on s3.

**Comment by ElliottLandsborough** [comment]
Closing the issue, syncing/caching fixed.

https://dog.ceo/api/breed/mix/images

**Comment by donavon** [comment]
I wanted to use this API in a demo, but was spooked away when I got a broken image. Thanks for fixing this!
